#!/usr/bin/env python3

"""
Build CIME component model library for EMULATORICE.
"""

import sys
import os

_CIMEROOT = os.environ.get("CIMEROOT")
if _CIMEROOT is None:
    raise ValueError("ERROR: CIMEROOT not defined.")
sys.path.append(os.path.join(_CIMEROOT, "scripts", "Tools"))
sys.path.append(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                             "..", "..", "cime_config"))

from standard_script_setup import *  # noqa: F401,F403,E402
from CIME.buildlib import (  # noqa: E402
    build_cime_component_lib,
    parse_input,
)
from CIME.case import Case  # noqa: E402


def buildlib(bldroot, libroot, case, compname=None):
    """ Build the emulatorice component library """
    if compname is None:
        compname = "emulatorice"

    build_cime_component_lib(case, compname, libroot, bldroot)


def _main_func(args):
    caseroot, libroot, bldroot = parse_input(args)
    with Case(caseroot) as case:
        buildlib(bldroot, libroot, case)


if __name__ == "__main__":
    _main_func(sys.argv)
