#!/usr/bin/env python3

"""
build eice library
"""
import sys, os

_CIMEROOT = os.environ.get("CIMEROOT")
if _CIMEROOT is None:
    raise SystemExit("ERROR: must set CIMEROOT environment variable")

_LIBDIR = os.path.join(_CIMEROOT, "scripts", "Tools")
sys.path.append(_LIBDIR)

from standard_script_setup import *
from CIME.buildlib         import parse_input
from CIME.case             import Case
from CIME.utils            import expect, run_bld_cmd_ensure_logging

logger = logging.getLogger(__name__)

###############################################################################
def buildlib(bldroot, installpath, case):
###############################################################################
    casebuild = case.get_value("CASEBUILD")
    caseroot  = case.get_value("CASEROOT")
    srcroot   = case.get_value("SRCROOT")

    filepaths = \
 """{caseroot}/SourceMods/src.eice
{srcroot}/components/emulator_comps/eice/src
""".format(caseroot=caseroot, srcroot=srcroot)

    confdir = os.path.join(casebuild, "eiceconf")
    if not os.path.isdir(confdir):
        os.makedirs(confdir)

    with open(os.path.join(casebuild, "eiceconf", "Filepath"), "w") as fd:
        fd.write(filepaths)

    with open(os.path.join(casebuild, "eiceconf", "CIME_cppdefs"), "w") as fd:
        fd.write("")

###############################################################################
def _main_func():
###############################################################################
    caseroot, libroot, bldroot = parse_input(sys.argv)
    with Case(caseroot, read_only=False) as case:
        buildlib(bldroot, libroot, case)

###############################################################################

if __name__ == "__main__":
    _main_func()
