name: test

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:

  e3sm-integration:
    strategy:
      fail-fast: false
      matrix:
        test:
          - ERIO_P4.ne30_g16_rx1.A.singularity_gnu
          - SMS_P4.ne4pg2_oQU480.WCYCL1850.singularity_gnu
    runs-on: ubuntu-latest

    steps:
      -
        name: Space
        run: |
          echo "Listing 100 largest packages"
          dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | tail -n 100
          df -h
          echo "Removing large packages"
          sudo apt-get remove -y '^dotnet-.*'
          sudo apt-get remove -y '^llvm-.*'
          sudo apt-get remove -y 'php.*'
          sudo apt-get remove -y '^mongodb-.*'
          sudo apt-get remove -y '^mysql-.*'
          sudo apt-get remove -y azure-cli google-cloud-sdk hhvm google-chrome-stable firefox powershell mono-devel libgl1-mesa-dri
          sudo apt-get autoremove -y
          sudo apt-get clean
          df -h
          echo "Removing large directories"
          # deleting 15GB
          rm -rf /usr/share/dotnet/
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h
      -
        name: QEMU
        uses: docker/setup-qemu-action@v3 
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false
          submodules: recursive
      - 
        name: CIME
        continue-on-error: true
        run: |
          mkdir -p $HOME/projects/e3sm/cesm-inputdata/atm/cam/physprops/
          wget https://web.lcrc.anl.gov/public/e3sm/inputdata/atm/cam/physprops/p3_lookup_table_1.dat-v4.1.2
          mv p3_lookup_table_1.dat-v4.1.2 $HOME/projects/e3sm/cesm-inputdata/atm/cam/physprops/
          docker run -v "${HOME}":"${HOME}","${PWD}":/app/ ghcr.io/mahf708/e3sm-imgs:v0.0.6 /bin/bash -c "export USER=test && cd /app/cime/scripts && ./create_test ${{ matrix.test }} --proc-pool 4 --wait --debug"
      - 
        name: Artifacts
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: ${{ matrix.test }}
          # Wildcard pattern to upload logs (can add more if desired)
          path: |
            ~/projects/e3sm/scratch/${{ matrix.test }}*/TestStatus.log
            ~/projects/e3sm/scratch/${{ matrix.test }}*/bld/*.bldlog.*
            ~/projects/e3sm/scratch/${{ matrix.test }}*/run/*.log.*
            ~/projects/e3sm/scratch/${{ matrix.test }}*/cprnc.out
            ~/projects/e3sm/scratch/${{ matrix.test }}*/test.${{ matrix.test }}*
