name: test

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:

  e3sm-integration:
    strategy:
      fail-fast: false
      matrix:
        test:
          - ERIO.ne30_g16_rx1.A.singularity_gnu
          - ERP_Ld3.ne30pg2_EC30to60E2r2.WCYCL1850.singularity_gnu.allactive-pioroot1
          - ERP_Ld9.ne4_ne4.FIDEAL.singularity_gnu.allactive-pioroot1
          - ERP_Ln18.ne4_oQU240.F2010.singularity_gnu
          - ERP_Ln9.ne4_ne4.FAQP.singularity_gnu
          - ERP_Ln9.ne4_ne4.FRCE.singularity_gnu
          - ERP_Ln9.ne4pg2_oQU480.WCYCL20TRNS-MMF1.singularity_gnu.allactive-mmf_fixed_subcycle
          - ERS.ELM_USRDAT.I1850ELM.singularity_gnu.elm-usrdat
          - ERS.ELM_USRDAT.IELM.singularity_gnu.elm-surface_water_dynamics
          - ERS.MOS_USRDAT.RMOSGPCC.singularity_gnu.mosart-mos_usrdat
          - ERS.MOS_USRDAT.RMOSNLDAS.singularity_gnu.mosart-sediment
          - ERS.f09_f09.IELM.singularity_gnu.elm-lnd_rof_2way
          - ERS.f09_g16.I1850ELMCN.singularity_gnu.elm-bgcinterface
          - ERS.f09_g16.I1850GSWCNPRDCTCBC.singularity_gnu.elm-vstrd
          - ERS.f09_g16.IELMBC.singularity_gnu
          - ERS.f09_g16.IELMBC.singularity_gnu.elm-simple_decomp
          - ERS.f09_g16_g.MALISIA.singularity_gnu
          - ERS.f19_f19.I1850ELMCN.singularity_gnu
          - ERS.f19_f19.I20TRELMCN.singularity_gnu
          - ERS.f19_g16.I1850CNECACNTBC.singularity_gnu.elm-eca
          - ERS.f19_g16.I1850CNECACTCBC.singularity_gnu.elm-eca
          - ERS.f19_g16.I1850CNRDCTCBC.singularity_gnu.elm-rd
          - ERS.f19_g16.I1850ELM.singularity_gnu.elm-betr
          - ERS.f19_g16.I1850ELM.singularity_gnu.elm-vst
          - ERS.f19_g16.I1850GSWCNPECACNTBC.singularity_gnu.elm-eca_f19_g16_I1850GSWCNPECACNTBC
          - ERS.f19_g16.I20TRGSWCNPECACNTBC.singularity_gnu.elm-eca_f19_g16_I20TRGSWCNPECACNTBC
          - ERS.f19_g16.I20TRGSWCNPRDCTCBC.singularity_gnu.elm-ctc_f19_g16_I20TRGSWCNPRDCTCBC
          - ERS.f19_g16_rx1.A.singularity_gnu
          - ERS.hcru_hcru.I20TRGSWCNPRDCTCBC.singularity_gnu.elm-erosion
          - ERS.ne30_g16_rx1.A.singularity_gnu
          - ERS.ne30pg2_r05_EC30to60E2r2.GPMPAS-JRA.singularity_gnu.mosart-rof_ocn_2way
          - ERS.ne4_oQU240.F2010.singularity_gnu.eam-thetahy_ftype2
          - ERS.ne4_oQU240.F2010.singularity_gnu.eam-thetanh_ftype2
          - ERS.ne4pg2_oQU480.WCYCL1850NS.singularity_gnu
          - ERS.r05_r05.IELM.singularity_gnu.elm-V2_ELM_MOSART_features
          - ERS.r05_r05.RMOSGPCC.singularity_gnu.mosart-gpcc_1972
          - ERS.r05_r05.RMOSGPCC.singularity_gnu.mosart-heat
          - ERS_D.f09_f09.IELM.singularity_gnu.elm-koch_snowflake
          - ERS_D.f09_f09.IELM.singularity_gnu.elm-solar_rad
          - ERS_D.f09_g16.I1850ELMCN.singularity_gnu
          - ERS_D.f19_f19.IELM.singularity_gnu.elm-ic_f19_f19_ielm
          - ERS_D.f19_g16.I1850GSWCNPRDCTCBC.singularity_gnu.elm-ctc_f19_g16_I1850GSWCNPRDCTCBC
          - ERS_D.ne11_oQU240.I20TRELM.singularity_gnu
          - ERS_D.ne4_oQU240.F2010.singularity_gnu.eam-hommexx
          - ERS_Ld20.f45_f45.IELMFATES.singularity_gnu.elm-fates
          - ERS_Ld3.ne30pg2_r05_EC30to60E2r2.WCYCL1850.singularity_gnu.allactive-nlmaps
          - ERS_Ld3.ne4_oQU240.F2010.singularity_gnu
          - ERS_Ld3.ne4pg2_oQU480.F2010.singularity_gnu.eam-thetahy_sl_pg2
          - ERS_Ld3.ne4pg2_oQU480.F2010.singularity_gnu.eam-thetahy_sl_pg2_ftype0
          - ERS_Ld5.T62_oQU120.CMPASO-NYF.singularity_gnu
          - ERS_Ld5.T62_oQU240.DTESTM.singularity_gnu
          - ERS_Ld5.ne4_oQU240.F2010.singularity_gnu.eam-rrtmgp
          - ERS_Ld5.ne4_oQU240.F2010.singularity_gnu.eam-rrtmgpxx
          - ERS_Ln9.ne4pg2_ne4pg2.F2010-MMF1.singularity_gnu.eam-mmf_crmout
          - ERS_Ln9.ne4pg2_ne4pg2.FRCE-MMF1.singularity_gnu.eam-cosp_nhtfrq9
          - NCK.f19_g16_rx1.A.singularity_gnu
          - NCK.ne4pg2_oQU480.WCYCL1850NS.singularity_gnu
          - PEM_Ln5.T62_oQU240wLI.DTESTM.singularity_gnu
          - PEM_Ln5.ne4_oQU240.F2010.singularity_gnu
          - PEM_Ln9.ne30pg2_EC30to60E2r2.WCYCL1850.singularity_gnu
          - PET.f19_g16.X.singularity_gnu.allactive-mach-pet
          - PET.f45_g37_rx1.A.singularity_gnu.allactive-mach-pet
          - PET_Ln5.T62_oQU240.DTESTM.singularity_gnu
          - PET_Ln5.ne4_oQU240.F2010.singularity_gnu.allactive-mach-pet
          - PET_Ln9_PS.ne30pg2_EC30to60E2r2.WCYCL1850.singularity_gnu.allactive-mach-pet
          - REP_Ln5.ne4_oQU240.F2010.singularity_gnu
          - SEQ.f19_g16.X.singularity_gnu
          - SMS.MOS_USRDAT.RMOSGPCC.singularity_gnu.mosart-unstructure
          - SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.singularity_gnu
          - SMS.f09_g16_a.IGELM_MLI.singularity_gnu
          - SMS.ne30_f19_g16_rx1.A.singularity_gnu
          - SMS.ne4_oQU240.F2010.singularity_gnu.eam-cosplite
          - SMS.ne4_oQU240.F2010.singularity_gnu.eam-preqx_ftype0
          - SMS.ne4_oQU240.F2010.singularity_gnu.eam-preqx_ftype1
          - SMS.ne4_oQU240.F2010.singularity_gnu.eam-preqx_ftype4
          - SMS.ne4_oQU240.F2010.singularity_gnu.eam-thetahy_ftype0
          - SMS.ne4_oQU240.F2010.singularity_gnu.eam-thetahy_ftype1
          - SMS.ne4_oQU240.F2010.singularity_gnu.eam-thetahy_ftype2
          - SMS.ne4_oQU240.F2010.singularity_gnu.eam-thetahy_ftype2_energy
          - SMS.ne4_oQU240.F2010.singularity_gnu.eam-thetahy_ftype4
          - SMS.ne4_oQU240.F2010.singularity_gnu.eam-thetahy_sl
          - SMS.ne4_oQU240.F2010.singularity_gnu.eam-thetanh_ftype0
          - SMS.ne4_oQU240.F2010.singularity_gnu.eam-thetanh_ftype1
          - SMS.ne4_oQU240.F2010.singularity_gnu.eam-thetanh_ftype2
          - SMS.ne4_oQU240.F2010.singularity_gnu.eam-thetanh_ftype4
          - SMS.r05_r05.I1850ELMCN.singularity_gnu.elm-qian_1948
          - SMS.r05_r05.IELM.singularity_gnu.elm-topounit
          - SMS_D_Ld1.TL319_EC30to60E2r2.DTESTM-JRA1p5.singularity_gnu.mpassi-jra_1958
          - SMS_D_Ld1.ne30pg2_EC30to60E2r2.WCYCL1850.singularity_gnu.allactive-wcprod
          - SMS_D_Ld1.ne30pg2_EC30to60E2r2.WCYCLSSP370.singularity_gnu.allactive-wcprodssp
          - SMS_D_Ld1.ne30pg2_r05_EC30to60E2r2.WCYCL1850.singularity_gnu
          - SMS_D_Ld3.T62_oQU120.CMPASO-IAF.singularity_gnu
          - SMS_D_Ln5.conusx4v1_r05_oECv3.F2010.singularity_gnu
          - SMS_D_Ln5.ne4_oQU240.F2010.singularity_gnu
          - SMS_D_Ln5.ne4_oQU240.F2010.singularity_gnu.eam-clubb_sp
          - SMS_D_Ln5.ne4_oQU240.F2010.singularity_gnu.eam-cosplite_nhtfrq5
          - SMS_Ld1.T62_oQU240wLI.GMPAS-IAF-DISMF.singularity_gnu
          - SMS_Ld1.hcru_hcru.I1850CRUELMCN.singularity_gnu
          - SMS_Ld1.ne4_ne4.FAQP.singularity_gnu.eam-clubb_only
          - SMS_Ld2.ne30pg2_r05_EC30to60E2r2.BGCEXP_CNTL_CNPECACNT_1850.singularity_gnu.elm-bgcexp
          - SMS_Ld2.ne30pg2_r05_EC30to60E2r2.BGCEXP_CNTL_CNPRDCTC_1850.singularity_gnu.elm-bgcexp
          - SMS_Ld20.f45_f45.IELMFATES.singularity_gnu.elm-fates_eca
          - SMS_Ld20_D.f45_f45.IELMFATES.singularity_gnu.elm-fates_rd
          - SMS_Ld30.f45_f45.IELMFATES.singularity_gnu.elm-fates_satphen
          - SMS_Ld9.ne4pg2_oQU480.F2010.singularity_gnu.eam-thetahy_sl_pg2_mass
          - SMS_Ln1.ne4_oQU240.F2010.singularity_gnu.eam-chem_pp
          - SMS_Ln3.ne4pg2_ne4pg2.F2010-MMF2.singularity_gnu
          - SMS_Ln5.ne30pg2_ne30pg2.F2010-SCREAM-LR-DYAMOND2.singularity_gnu
          - SMS_Ln5.ne30pg2_r05_EC30to60E2r2.BGCEXP_LNDATM_CNPRDCTC_1850.singularity_gnu
          - SMS_Ln5.ne30pg2_r05_EC30to60E2r2.BGCEXP_LNDATM_CNPRDCTC_20TR.singularity_gnu
          - SMS_Ln5.ne4_ne4.FSCM-ARM97-MMF1.singularity_gnu
          - SMS_Ln5.ne4pg2_oQU480.F2010.singularity_gnu
          - SMS_Ln5.ne4pg2_oQU480.F2010.singularity_gnu.eam-thetahy_pg2
          - SMS_Ln5.ne4pg2_oQU480.F2010.singularity_gnu.eam-thetahy_sl_pg2
          - SMS_Ln5.ne4pg2_oQU480.F2010.singularity_gnu.eam-thetahy_sl_pg2_ftype0
          - SMS_Ln9.ne4_oQU240.F2010.singularity_gnu.eam-outfrq9s
          - SMS_Ln9_P24x1.ne4_ne4.FDPSCREAM-ARM97.singularity_gnu
          - SMS_Ly2_P1x1.1x1_smallvilleIA.IELMCNCROP.singularity_gnu.elm-fan
          - SMS_Ly2_P1x1.1x1_smallvilleIA.IELMCNCROP.singularity_gnu.elm-force_netcdf_pio
          - SMS_Ly2_P1x1.1x1_smallvilleIA.IELMCNCROP.singularity_gnu.elm-per_crop
          - SMS_Ly2_P1x1_D.1x1_smallvilleIA.IELMCNCROP.singularity_gnu.elm-lulcc_sville
          - SMS_P12x2.ne4_oQU240.WCYCL1850NS.singularity_gnu.allactive-mach_mods
          - SMS_R_Ld5.ne4_ne4.FSCM-ARM97.singularity_gnu.eam-scm
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/mahf708/e3sm-imgs:v0.0.6

    steps:
      -
        name: Space
        run: |
          echo "Listing 100 largest packages"
          dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | tail -n 100
          df -h
          echo "Removing large packages"
          sudo apt-get remove -y '^dotnet-.*'
          sudo apt-get remove -y '^llvm-.*'
          sudo apt-get remove -y 'php.*'
          sudo apt-get remove -y '^mongodb-.*'
          sudo apt-get remove -y '^mysql-.*'
          sudo apt-get remove -y azure-cli google-cloud-sdk hhvm google-chrome-stable firefox powershell mono-devel libgl1-mesa-dri
          sudo apt-get autoremove -y
          sudo apt-get clean
          df -h
          echo "Removing large directories"
          # deleting 15GB
          rm -rf /usr/share/dotnet/
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h
      - 
        name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false
          submodules: recursive
      - 
        name: CIME
        working-directory: cime/scripts
        continue-on-error: true
        run: |
          mkdir -p $HOME/projects/e3sm/cesm-inputdata/atm/cam/physprops/
          wget https://web.lcrc.anl.gov/public/e3sm/inputdata/atm/cam/physprops/p3_lookup_table_1.dat-v4.1.2
          mv p3_lookup_table_1.dat-v4.1.2 $HOME/projects/e3sm/cesm-inputdata/atm/cam/physprops/
          export USER=test
          ./create_test ${{ matrix.test }} --proc-pool 4 --wait --debug
      - 
        name: Artifacts
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: ${{ matrix.test }}
          # Wildcard pattern to upload logs (can add more if desired)
          path: |
            ~/projects/e3sm/scratch/**/*log.*
