name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:

  run:
    strategy:
      fail-fast: false
      matrix:
        typ: 
          - "SMS_P4"   # 0h20m
          - "REP_P4"   # 0h30m
          - "ERS_P4"   # 1h00m
          - "ERP_P4"   # 1h15m
          - "ERI_P4" # Exception from case_test: [Errno 2] No such file or directory:
          - "ERT_P4" # Exception from case_test: ERROR: No variable AVG_HIST_N found in case
          - "ERR_P4"   # 1h00m
          - "PET_P4"   # 0h35m
          - "PEM_P4"   # 0h45m
          - "PEA_P4" # ERROR: BUILD FAIL: build e3sm failed
          - "SEQ_P4" # 3h00m+
          - "SMS_D_P4"   # 0h20m
          - "REP_D_P4"   # 0h30m
          - "ERS_D_P4"   # 1h00m
          - "ERP_D_P4"   # 1h15m
          - "ERI_D_P4" # Exception from case_test: [Errno 2] No such file or directory:
          - "ERT_D_P4" # Exception from case_test: ERROR: No variable AVG_HIST_N found in case
          - "ERR_D_P4"   # 1h00m
          - "PET_D_P4"   # 0h35m
          - "PEM_D_P4"   # 0h45m
          - "PEA_D_P4" # ERROR: BUILD FAIL: build e3sm failed
          - "SEQ_D_P4" # 3h00m+
        res: ["ne4pg2_oQU480", "ne30pg2_r05_IcoswISC30E3r5"]
        com: ["F2010"]
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/mahf708/e3sm-imgs:v0.0.6

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false
          submodules: recursive
      - name: CIME
        working-directory: cime/scripts
        run: |
          mkdir -p $HOME/projects/e3sm/cesm-inputdata/atm/cam/physprops/
          wget https://web.lcrc.anl.gov/public/e3sm/inputdata/atm/cam/physprops/p3_lookup_table_1.dat-v4.1.2
          mv p3_lookup_table_1.dat-v4.1.2 $HOME/projects/e3sm/cesm-inputdata/atm/cam/physprops/
          export USER=test
          ./create_test ${{ matrix.typ }}.${{ matrix.res }}.${{ matrix.com }} --machine singularity --wait --debug
