name: SMS_Ln1.ne4_oQU480.F2010.linux-generic

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

jobs:

  build:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/mahf708/e3sm-imgs:main
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: CIME
        working-directory: cime/scripts
        run: |
          mkdir -p $HOME/projects/e3sm/cesm-inputdata
          ./create_test SMS_Ln1.ne4_oQU480.F2010 --machine linux-generic --no-run --input-dir $HOME/projects/e3sm/cesm-inputdata
