name: SMS_Ln1.ne4_oQU480.F2010.linux-generic

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          init-shell: bash
          environment-name: cime-env
          create-args: >-
            python=3.10
            libnetcdf=*=*mpich*
            netcdf-fortran
            libxml2
            compilers
            mpich
            make
            cmake
      - name: CIME
        working-directory: cime/scripts
        run: |
          micromamba activate cime-env
          ln -s $CONDA_PREFIX/bin/make $CONDA_PREFIX/bin/gmake
          export NETCDF_PATH=$CONDA_PREFIX/lib/libnetcdf.so
          mkdir -p $HOME/projects/e3sm/cesm-inputdata
          ./create_test SMS_Ln1.ne4_oQU480.F2010 --machine linux-generic --no-run --input-dir $HOME/projects/e3sm/cesm-inputdata
          cat $HOME/projects/acme/scratch/SMS_Ln1.ne4_oQU480.F2010.linux-generic_gnu.*/bld/mct.bldlog.*

  # run:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         submodules: recursive
  #     - name:
  #       uses: mamba-org/setup-micromamba@v1
  #       with:
  #         init-shell: bash
  #         environment-name: cime-env
  #         create-args: >-
  #           python=3.10
  #           libnetcdf
  #           netcdf-fortran
  #           libxml2
  #           compilers
  #           mpich
  #           make
  #           cmake
  #     - name: Build with CIME
  #       working-directory: cime/scripts
  #       run: |
  #         micromamba activate cime-env
  #         ln -s $CONDA_PREFIX/bin/make $CONDA_PREFIX/bin/gmake
  #         mkdir -p $HOME/projects/e3sm/cesm-inputdata
  #         ./create_test SMS_Ln1.ne4_oQU480.F2010 --debug --machine linux-generic --verbose --input-dir $HOME/projects/e3sm/cesm-inputdata
