name: SMS_Ln1.ne4_oQU480.F2010.linux-generic

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

jobs:

  build:
    runs-on: ubuntu-20.04
    container: 
      image: ghcr.io/mahf708/e3sm-imgs:main
    steps:
      - name: addenda
        run: |
          apt-get update
          apt-get -y install python3-distutils
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: CIME
        working-directory: cime/scripts
        run: |
          mkdir -p $HOME/projects/e3sm/cesm-inputdata
          export USER=test
          export NETCDF_PATH=/usr/local/packages/netcdf-serial/lib/libnetcdf.a
          ./create_test SMS_Ln1.ne4_oQU480.F2010 --machine linux-generic --input-dir $HOME/projects/e3sm/cesm-inputdata --no-batch --wait
          cat /github/home/projects/acme/scratch/SMS_Ln1.ne4_oQU480.F2010.linux-generic_gnu.*/bld/cprnc.bldlog.*