name: test

on:
  # Runs every time master branch is updated
  push:
    branches: ["master"]
  # Runs every time a PR is open against master
  pull_request:
    branches: ["master"]
  workflow_dispatch:

defaults:
    run:
        shell: bash -l {0}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name:
        uses: mamba-org/setup-micromamba@v1
        with:
          init-shell: bash
          environment-name: cime-env
          create-args: >-
            python=3.10
            libnetcdf
            libxml2
      - name: Build with CIME
        working-directory: cime/scripts
        run: |
          micromamba activate cime-env
          ./create_test SMS.ne4_oQU480.F2010 --wait