name: SMS_Ln1.ne4_oQU480.F2010.linux-generic

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

jobs:

  build:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/mahf708/e3sm-imgs:main
    steps:
      - name: addenda
        run: |
          apt-get update
          apt-get -y install python3-distutils
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: patch config_machines.xml
        working-directory: cime_config/machines/
        run : |
          cat << EOF >> some.patch
          diff --git a/cime_config/machines/config_machines.xml b/cime_config/machines/config_machines.xml
          --- cime_config/machines/config_machines.xml
          +++ cime_config/machines/config_machines.xml
          @@ -1236,18 +1236,17 @@
                 <env name="E3SM_SRCROOT">$SRCROOT</env>
               </environment_variables>
               <environment_variables mpilib="mpi-serial">
                 <env name="NETCDF_PATH">/usr/local/packages/netcdf-serial</env>
          -      <env name="PATH">/usr/local/packages/cmake/bin:/usr/local/packages/hdf5-serial/bin:/usr/local/packages/netcdf-serial/bin:$ENV{PATH}</env>
          -      <env name="LD_LIBRARY_PATH">/usr/local/packages/szip/lib:/usr/local/packages/hdf5-serial/lib:/usr/local/packages/netcdf-serial/lib</env>
          +      <env name="PATH">/usr/local/packages/cmake/bin:/usr/local/packages/hdf5-1.10.6-serial/bin:/usr/local/packages/netcdf-serial/bin:$ENV{PATH}</env>
          +      <env name="LD_LIBRARY_PATH">/usr/local/packages/szip/lib:/usr/local/packages/hdf5-1.10.6-serial/lib:/usr/local/packages/netcdf-serial/lib</env>
               </environment_variables>
               <environment_variables mpilib="!mpi-serial">
                 <env name="NETCDF_PATH">/usr/local/packages/netcdf-parallel</env>
                 <env name="PNETCDF_PATH">/usr/local/packages/pnetcdf</env>
                 <env name="HDF5_PATH">/usr/local/packages/hdf5-parallel</env>
          -      <env name="PATH">/usr/local/packages/cmake/bin:/usr/local/packages/mpich/bin:/usr/local/packages/hdf5-parallel/bin:/usr/local/packages/netcdf-parallel/bin:/usr/local/packages/pnetcdf/bin:$ENV{PATH}</env>
          -      <env name="LD_LIBRARY_PATH">/usr/local/packages/mpich/lib:/usr/local/packages/szip/lib:/usr/local/packages/hdf5-parallel/lib:/usr/local/packages/netcdf-parallel/lib:/usr/local/packages/pnetcdf/lib</env>
          -    </environment_variables>
          +      <env name="PATH">/usr/local/packages/cmake/bin:/usr/local/packages/mpich-3.3.2/bin:/usr/local/packages/hdf5-1.10.6-parallel/bin:/usr/local/packages/netcdf-parallel/bin:/usr/local/packages/pnetcdf-1.12.1/bin:$ENV{PATH}</env>
          +      <env name="LD_LIBRARY_PATH">/usr/local/packages/mpich-3.3.2/lib:/usr/local/packages/szip-2.1.1/lib:/usr/local/packages/hdf5-1.10.6-parallel/lib:/usr/local/packages/netcdf-parallel/lib:/usr/local/packages/pnetcdf-1.12.1/lib</env>    </environment_variables>
             </machine>
           
             <machine MACH="melvin">
               <DESC>Linux workstation for Jenkins testing</DESC>
          
          EOF
          git apply some.patch -v
      - name: CIME
        working-directory: cime/scripts
        run: |
          mkdir -p $HOME/projects/e3sm/cesm-inputdata
          export USER=test
          ./create_newcase --case master.WCYCL1850.ne4_oQU240.baseline --compset WCYCL1850 --res ne4_oQU240 --machine singularity
          cd master.WCYCL1850.ne4_oQU240.baseline
          ./case.setup
          ./case.build -v
          # cat /github/home/projects/e3sm/scratch/master.WCYCL1850.ne4_oQU240.baseline/bld/e3sm.bldlog.*
          # ./case.run
