name: SMS_Ln1.ne4_oQU480.F2010.linux-generic

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}
jobs:
  SMS-ne4_oQU480:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name:
        uses: mamba-org/setup-micromamba@v1
        with:
          init-shell: bash
          environment-name: cime-env
          create-args: >-
            python=3.10
            libnetcdf
            libxml2
      - name: Build with CIME
        working-directory: cime/scripts
        run: |
          micromamba activate cime-env
          mkdir -p $HOME/projects/e3sm/cesm-inputdata
          ./create_test SMS_Ln1.ne4_oQU480.F2010 --debug --machine linux-generic
